### ISSUE TITLE
Architecture Diagram Visualization

### ISSUE THREAD

**Issue by afonsoppedro** [mreferre/yelb#21]
Hi @mreferre,

I’m Afonso and I came across your repo and I took the liberty to scan it with the tool that I am currently developing. If I caught your attention, feel free to take a look at the [following diagram](https://dashboard.codeshield.io/public/result/11ea06b1-37be-4816-9c20-762534f9cd39?utm_source=github.com&utm_medium=share-graphs&utm_campaign=teamb) and let me know your thoughts on this. I am really interested to get your feedback and understand if the diagram we presented matches the architecture you have in mind.

**Comment by mreferre** [comment]
Thanks. I think I am not sure it captures the essence of it. I will say though that this repo is a bit unique in the sense it mixes source code + multiple IaC options (to deploy said code). I use this repo for demo purposes to show how you can take the same app and deploy it to multiple type of infrastructures/stacks. The resulting diagram kind of melts these various options and isn't very clear IMO.

**Comment by afonsoppedro** [comment]
Thanks for letting me know @mreferre ! That's why those dangling EC2 instances appear in the diagram, right? Ignoring those for now, does the Lambda / Serverless part of the diagram resemble the potential connectivity between the resources of your stacks?

Do you have other repositories containing CloudFormation files, that'd be worth a look at?

**Comment by mreferre** [comment]
Yeah if you get rid of the EC2 instances in the diagram the remaining resembles the architecture of the serverless deployment.
