### ISSUE TITLE
Error in starting yelb-db_1  container

### ISSUE THREAD

**Issue by 1vinodsingh1** [mreferre/yelb#57]
It gives error:

yelb-db_1         | runtime: failed to create new OS thread (have 2 already; errno=22)
yelb-db_1         | fatal error: newosproc

I'm running on "localtest" deployment using docker-compose. My local environment is MacOS Monterey version 12.6 Chip: Apple M1.

**Comment by mreferre** [comment]
https://github.com/mreferre/yelb/commit/e1d8cbcd0d8d3ffb1a868ffe14e523261b047f4b
