### ISSUE TITLE
Helm chart references invalid container image

### ISSUE THREAD

**Issue by igitcode** [mreferre/yelb#7]
The deployment template for yelb-ui references image "nomisbeme/yelb-ui:0.6", which is an invalid image. Updating image name to "mreferre/yelb-ui:0.6" fixed the issue.

**Comment by mreferre** [comment]
Thanks for spotting this and reporting. If you intend to open a PR I will merge the code unless I will do it. Thanks again.

**Comment by unixerius** [comment]
I assume this has already been fixed. Let's close this issue.

**Comment by mreferre** [comment]
Good catch. Thanks.
