### ISSUE TITLE
Kubernetes deployments, yelb-ui fails to stay up

### ISSUE THREAD

**Issue by unixerius** [mreferre/yelb#71]
Thanks for sharing this cool project!

I've been trying out the various files under https://github.com/mreferre/yelb/tree/master/deployments/platformdeployment/Kubernetes/yaml

I'm using a Kubernetes cluster in my homelab, plain vanilla K8S on Alpine Linux.

I've been trying the various deployments that should work on a local cluster (not in the cloud) and none of them work. In all tests so far, the UI server fails to stay up. 

The logs from the yelb-ui container tell me:
`[emerg] 11#11 host not found in upstream "yelb-appserver" in /etc/nginx/conf.d/default.conf:5`

It's true, the yelb-appserver container needs a while to startup, but even when it's up the yelb-ui container will say it can't find the appserver.

**Comment by unixerius** [comment]
I realized this issue is the same, or similar, to https://github.com/mreferre/yelb/issues/36

**Comment by mreferre** [comment]
Hi there. Sorry for the problem. Which K8s are you testing with? I think the K8s yaml files in the repo right now would need a bit of hammering if you are using K8s 1.23 or above (maybe even 1.22). 

It's something I would need to check (it was on my to-do but I did not get to it yet). 

I also think the problem in #36 is unrelated (probably similar outcome but different cause).

**Comment by unixerius** [comment]
Using the most recent version on my Alpine, which is 1.26. I'll go and see if maybe an older version would be more cooperative. Still, most of the setup works, it's just that the Yelb-ui pod can't find the yelb-appserver pod. I'm trying to figure out why.

**Comment by mreferre** [comment]
In general the reason why the `yelb-ui` container would not stay up is because it can't reach the `yelb-appserver` service on port 4567. [This](https://github.com/mreferre/yelb/blob/master/yelb-ui/startup.sh#L5-L20) is the part of the code involved (by default the NGINX proxy is configured to ... proxy to `http://yelb-appserver:4567` and if it can't reach it it will fail to start and it will bring down the container with it). 

I haven't tested minikube in a long time with that yaml (I should build more automation to test the various yaml files on their respective backends) and it could be possible that I'd need to fix them (I created those around the 1.1x K8s timeframe IIRC).

**Comment by unixerius** [comment]
I read some article earlier which suggested using a different config for NGinx, where instead of defining with an upstream, you'd instead set it to a "dumber" proxy mode where it doesn't test for the upstream system... Alternatively, the yelb-ui pod could be adjusted to include an initContainer which waits for the appserver to be available.

I'm currently trying to get the latter to work.

**Comment by mreferre** [comment]
While I want to attack the testing/automation problem alluded above (at some point), I am indeed interested in your first option to find a way to make NGINX behave less aggressively when the endpoint is not available. The current scenario is not ideal for proper troubleshooting and I would rather too that the container stayed up when the `yelb-appserver` endpoint is not reachable. If you find anything useful I'd love to hear. 

The sidecar option is less palatable for me (but if it works for you great!).

**Comment by unixerius** [comment]
I don't fully understand the setup, as I have next-to-none NGinx experience, but this is what I was looking at -> https://www.prasanna.dev/posts/start-nginx-when-upstream-unavailable

**Comment by mreferre** [comment]
I am no NGINX expert either. My understanding is that the `resolver` directive can help in that NGINX fails when it can't resolve the endpoint (i.e. if you use an IP you won't have this problem) but this makes the deployment very dependent of the underneath infrastructure. I would need to research more. More background in [this SO thread](https://stackoverflow.com/questions/32845674/setup-nginx-not-to-crash-if-host-in-upstream-is-not-found).

**Comment by unixerius** [comment]
In the mean time, it turns out it's also not about startup timing. Because even if I force the yelb-ui pod to wait for the yelb-appserver and its service to be ready, it still says it can't find it. 

This is frustrating. I feel like I should just understand why the yelb-ui pod cannot resolve the name for the yelb-appserver service. But... I don't. :D

**Comment by mreferre** [comment]
Sorry you are going through this pain. I have just tested the `yelb-k8s-minikube-ingress.yaml` and the `yelb-k8s-minikube-nodeport.yaml` on a Docker Desktop running on a Mac and they work just fine as-is. DD deploys a local K8s 1.25 cluster (I thought I had to hammer the yamls a bit but they just worked). 

I am wondering if the problem you see with the yelb-ui container not stabilizing is a symptom of a larger issue you have. Does it have coredns setup? 

For example would the following work for you? Basically you could `exec` into the appserver and curl itself to see if it can reach out to the backend to read the votes. If this doesn't work name resolution just doesn't work IMO.   

```
% kubectl exec -it yelb-appserver-5d8db45799-z56zn -- bash
root@yelb-appserver-5d8db45799-z56zn:/# curl yelb-appserver:4567/api/getvotes
[{"name": "outback", "value": 2},{"name": "bucadibeppo", "value": 0},{"name": "ihop", "value": 0}, {"name": "chipotle", "value": 0}]
```

**Comment by unixerius** [comment]
I will test this tonight, when I'm at home. I agree with you, this very much appears to be a "me"-problem, with my environment. Thank you for helping with the troubleshooting, I really appreciate it.

**Comment by mreferre** [comment]
Pleasure. I really want you to make it work :) 

Let me know.

**Comment by unixerius** [comment]
Yeah, the yelb-appserver can't curl itelf either, can't resolve the name.

Mind you, it can't curl localhost either. But yeah, my K8S setup is suspicious here.

**Comment by unixerius** [comment]
This is interesting: I loaded the dnsutils container as per the K8S documentation -> https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

From THAT pod I can properly resolve the Yelb DNS names. But not from the Yelb pods themselves!

**Comment by unixerius** [comment]
I'm closing this issue, as the problem is clearly in my dev env.
