### ISSUE TITLE
ECS EC2 Deployment - Cloudformation Time Out error

### ISSUE THREAD

**Issue by sushreeswetanjali99** [mreferre/yelb#76]
Hi, 

We are deploying the Cloudformation template to deploy yelb in an ECS cluster running on EC2. 

The template is timing out at the creation of Services in the cluster for UI, App, Redis and DB. 

![cfn1](https://user-images.githubusercontent.com/84499149/227959477-bf800592-72ee-4470-bf4f-94f1869a0c67.PNG)

![cfndeploy](https://user-images.githubusercontent.com/84499149/227959601-a04879d6-558a-4f8d-ba07-ba37ed1d2468.PNG)

On checking the ECS cluster we found that there were no Container Instances launched.

![containerinstance](https://user-images.githubusercontent.com/84499149/227959729-c745c71d-7c2d-43d6-a837-b2b31b3780bf.PNG)

Are we missing something in the CFN? Because the 4 services failed due to a lack of container instances. 

Could you please help us with this issue. 

Thanks

**Comment by mreferre** [comment]
Hey there. Yes the CFN templates assumes the cluster already exists. If you use Fargate you don't need much else but if you use EC2 you need to deploy 1+ EC2 Container Instances and attach them to the cluster to provide capacity. This is outside of the goal of this CFN template. I should perhaps make it clear in the [README](https://github.com/mreferre/yelb/blob/master/deployments/platformdeployment/AWS/ECS/cfn/README.md).

**Comment by sushreeswetanjali99** [comment]
Thanks. I have created a 2 container instances of m5.large and registered with the cluster. 

The appserver, DB and redis services launched successfully. But the UI service is erroring out with exit code 1.

![image](https://user-images.githubusercontent.com/84499149/228161022-a9a7cd31-94c1-49f5-8c36-316d7613a61a.png)

![image](https://user-images.githubusercontent.com/84499149/228161098-ab7357f1-8456-4a66-97ae-32760ad4d4b3.png)

It is unable to find the yelb-appserver in the nginx conf looks like. Is this related to the startup script for UI?

**Comment by mreferre** [comment]
Mh... let me test this.

**Comment by mreferre** [comment]
Weird. I just tested it and it works fine with instances deployed to the default VPC. It looks like name resolution isn't working properly. Is it possible that your VPC is configured in a way that disables DNS resolution? This is usually a reason why this scenario fails. Also, does this work if you try to deploy to Fargate (Vs EC2)?

**Comment by sushreeswetanjali99** [comment]
I just checked, the vpc has DNS resolution enabled. Only DNS hostnames are disabled.

![image](https://user-images.githubusercontent.com/84499149/228242846-be45b426-d5f4-4e3c-bc1a-c0815f243f5f.png)

**Comment by sushreeswetanjali99** [comment]
Sure, will test the script for Fargate and get back to you. Thanks a lot for the immediate response, we greatly appreciate your help!

**Comment by mreferre** [comment]
Absolutely. I am sorry you are going through this. I'd love to help more.

**Comment by sushreeswetanjali99** [comment]
Hey,

We launched the Fargate cluster but got the same error - the UI service fails in connecting to the app server

![image](https://user-images.githubusercontent.com/84499149/228554332-3a8dd757-3ec1-4b7e-abc7-d2a7cc584834.png)

**Comment by mreferre** [comment]
Mh... there is something going on here. First I assume you are using the stock CFN template provided in the repo (no changes)? What is the domain you set as an input? Can you show me how the R53 zone associated to that domain looks like? (please make sure that you do not capture confidential information). Can you also show me how the `yelb-appserver` service instances in the Cloud Map namespace that corresponds to the domain? Like for me these are the two tasks in the `yelb-appserver` Cloud Map service. 

![image](https://user-images.githubusercontent.com/4123965/228616395-0d9ab131-41e0-4584-b949-de31bdd5641a.png)

**Comment by sushreeswetanjali99** [comment]
Hey,

Yes we are using the stock CFN template for ECS, no changes. 

This is how the configuration looks:

1. Route 53:
![image](https://user-images.githubusercontent.com/84499149/228769504-f9f5e515-1475-4a04-bc05-6d919cb8711d.png)

2. Cloud Map Services:
![image](https://user-images.githubusercontent.com/84499149/228769598-f9290f66-d4be-4455-9ba2-76ca096ebe6a.png)

3. Cloud Map App Server Service: Only one task is listed 

![image](https://user-images.githubusercontent.com/84499149/228769691-9dbf69dd-4d38-4dda-a28e-66289977cffc.png)

4. Cloud Map UI Server Service: Unhealthy

![image](https://user-images.githubusercontent.com/84499149/228769779-19a1dd9c-f837-4d75-bdf2-88d2d2e6b585.png)

**Comment by sushreeswetanjali99** [comment]
oh, on our side the R53 doe not have any entries for UI. 

this is the script we are using, no modifications - https://github.com/mreferre/yelb/blob/master/deployments/platformdeployment/AWS/ECS/cfn/yelb-cloudformation-ECS-deployment.yaml 

The CFN is stuck at this stage and in Cloud Map there are no service instances listed for UI. 

![image](https://user-images.githubusercontent.com/84499149/228811167-b9244c77-97bb-46f1-a266-744c776d3f02.png)

Not sure if there is a limitation issue.

Thanks again!

**Comment by mreferre** [comment]
Mh... if you are using Fargate makes sure that your limits allows you to deploy all your tasks. You can check the `Quotas` in the AWS console (search for `quotas` and then look for Fargate as the service). 

If you go into the ECS Console and you explore the `yelb-ui` service do you see anything in particular? Especially in the `Health and metrics`, `Configurations and tasks`, `Deployment and events`, etc.

**Comment by mreferre** [comment]
Also, I doubt that the Fargate quota is the problem because 1) you showed the container logs above so that task has been deployed and 2) you seemed to have the same problem when deploying to EC2. In addition to exploring the ECS console (see above) does the CFN stack say anything interesting? What are the`Resources` that are still pending the deployment? Does the `Events` tab say anything interesting?

**Comment by sushreeswetanjali99** [comment]
Hey,
  I have checked health and metrics of ui server.
![image](https://user-images.githubusercontent.com/84499149/228866591-862bb9d7-9754-4978-9341-f42180be8d61.png)
Configuration and task
![image](https://user-images.githubusercontent.com/84499149/228866914-919a52f9-0182-42d3-89d5-fc36a7242f31.png)
deployment and events:
![image](https://user-images.githubusercontent.com/84499149/228867170-d4b13f05-631e-4dfc-afa0-5e618947aa6b.png)
And only ui server is pending , not running in the cfn stack.
![image](https://user-images.githubusercontent.com/84499149/228867936-b70de831-a5a5-4cf1-b23a-6f62f6ae770e.png)

**Comment by sushreeswetanjali99** [comment]
Yeah I will test the cfn in another account with default vpc , and get back to you.

**Comment by sushreeswetanjali99** [comment]
Hey we found the problem, DNS Hostname was disabled on the VPC. After enabling it, we launched the template and it ran successfully! Thanks a lot for the help. really appreciate it. We will test this for EC2 now. 
![image](https://user-images.githubusercontent.com/84499149/229077919-78f2e237-d68b-4d30-bfd8-fafab6d079d8.png)

**Comment by mreferre** [comment]
Closing this.

**Comment by sushreeswetanjali99** [comment]
Hey, 
 Sorry to trouble you again, but in ec2-ecs deployment I m getting error. Before deploying the cfn, I have created two m5large instance, I have given ecs credential in the ec2 but it failed.
![image](https://user-images.githubusercontent.com/84499149/229447103-6f36b7d6-c5dc-4592-9237-409600a7bb8d.png)

**Comment by mreferre** [comment]
Mh... looks like a problem with the setup of the instances and the ECS agent. Not sure if the role has anything to do with it. The new ECS console allows you to create the ASG + ECS container instances as part of cluster creation. My suggestion would be to start there for a test.

**Comment by sushreeswetanjali99** [comment]
Ok will check and let you know.
